services:

  camunda-data-init:
    image: camunda/camunda:${CAMUNDA_VERSION}
    user: "0:0"
    entrypoint: ["/bin/sh", "-c", "chown -R 1001:1001 /usr/local/camunda/camunda-data && chmod 775 /usr/local/camunda/camunda-data"]
    volumes:
      - camunda-data:/usr/local/camunda/camunda-data
    restart: "no"

  orchestration:
    image: camunda/camunda:${CAMUNDA_VERSION}
    container_name: orchestration
    ports:
      - "26500:26500"
      - "9600:9600"
      - "8083:8080"
    environment:
      - JAVA_TOOL_OPTIONS="-XX:+PrintFlagsFinal"
    mem_limit: 1g
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'exec 3<>/dev/tcp/127.0.0.1/9600 && echo -e \"GET /actuator/health/status HTTP/1.1\r\nHost: localhost\r\n\r\n\" >&3 && head -n 1 <&3'"]
      interval: 30s
      retries: 30
      start_period: 180s
    volumes:
      - zeebe:/usr/local/zeebe/data
      - camunda-data:/usr/local/camunda/camunda-data
      - ./driver-lib:/driver-lib:ro
    configs:
      - source: orchestration-config
        target: /usr/local/camunda/config/application.yaml
    networks:
      - camunda
      - acme-net
    depends_on:
      camunda-data-init:
        condition: service_completed_successfully
  
  connectors:
    image: camunda/connectors-bundle:${CAMUNDA_CONNECTORS_VERSION}
    container_name: connectors
    ports:
      - "8086:8080"
    environment:
      - management.endpoints.web.exposure.include=health,configprops
      - management.endpoint.health.probes.enabled=true
    env_file: connector-secrets.txt
    mem_limit: 512m
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/actuator/health/readiness"]
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 30s
    configs:
      - source: connectors-config
        target: application.yaml
    networks:
      - camunda
    depends_on:
      orchestration:
        condition: service_healthy

  rental-service:
    build:
      context: ./rental-service
      dockerfile: Dockerfile.dev
    container_name: rental-service
    environment:
        ZEEBE_CLIENT_BROKER_GATEWAYADDRESS: orchestration:26500
        ZEEBE_CLIENT_SECURITY_PLAINTEXT: true
        SPRING_PROFILES_ACTIVE: docker
        SPRING_DATASOURCE_URL: jdbc:postgresql://rental-service-db:5432/acme_mobility
        SPRING_DATASOURCE_USERNAME: user
        SPRING_DATASOURCE_PASSWORD: password
        SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    ports:
      - "8080:8080"
    volumes: 
      - ./rental-service:/app
      - maven-cache:/root/.m2
    networks:
      - acme-net
    depends_on:
      orchestration:
        condition: service_healthy
      rental-service-db:
          condition: service_healthy

  rental-service-db:
    image: postgres:18
    container_name: rental-service-db
    environment:
        POSTGRES_DB: acme_mobility
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./rental-service/db/:/docker-entrypoint-initdb.d
      - rental-service-data:/var/lib/postgresql
    networks:
      - acme-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d acme_mobility"] 
      interval: 5s
      timeout: 5s
      retries: 10

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - acme-net
    depends_on:
      - rental-service

  bank-service:
    build:
      context: ./bank-service
      dockerfile: Dockerfile.dev
    container_name: bank-service
    ports:
      - "8000:8000"
    volumes:
      - ./bank-service:/app
    restart: unless-stopped
    depends_on:
      bank-service-db:
        condition: service_healthy
    networks:
      - acme-net

  bank-service-db:
    image: postgres:18
    container_name: bank-service-db
    environment:
        POSTGRES_DB: bank
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - ./bank-service/db/:/docker-entrypoint-initdb.d
      - bank-service-data:/var/lib/postgresql
    networks:
      - acme-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bank"] 
      interval: 5s
      timeout: 5s
      retries: 10
      
  bank-account-registration-service:
    build:
      context: ./bank-account-registration-service
      dockerfile: Dockerfile.dev
    container_name: bank-account-registration-service
    ports:
      - "8082:8080" 
    volumes:
      - ./bank-account-registration-service:/app
    restart: unless-stopped
    depends_on:
      bank-service-db:
        condition: service_healthy
    networks:
      - acme-net

  fm-gateway:
    build:
      context: ./fleet-management-service
      dockerfile: fm-gateway/Dockerfile
    container_name: fm-gateway
    ports:
      - "8091:8081"
    networks:
      - acme-net
      - fleet-management-net
    depends_on:
      - tracking-service
      - battery-service
    environment:
      - SERVER_PORT=8081
      - TRACKING_SERVICE_URL=tracking-service:8082
      - BATTERY_SERVICE_URL=battery-service:8083

  tracking-service:
    build:
      context: ./fleet-management-service
      dockerfile: tracking-service/Dockerfile
    container_name: tracking-service
    expose:
      - "8082"
    ports:
      - "8092:8082"
    networks:
      - fleet-management-net
    environment:
      - SERVER_PORT=8082
      - GRPC_SERVER_PORT=9092

  battery-service:
    build:
      context: ./fleet-management-service
      dockerfile: battery-service/Dockerfile
    container_name: battery-service
    expose:
      - "8083"
    ports:
      - "8093:8083"
    networks:
      - fleet-management-net
    environment:
      - SERVER_PORT=8083
      - GRPC_SERVER_PORT=9093

networks:
  camunda:
  acme-net:
    driver: bridge
  fleet-management-net:
    driver: bridge

volumes:
  zeebe:
  camunda-data:
  maven-cache:
  rental-service-data:
  bank-service-data:

configs:
  connectors-config:
    content: |
      camunda:
        client:
          mode: self-managed
          grpc-address: http://orchestration:26500
          rest-address: http://orchestration:8080

  orchestration-config:
    file: ./application.yaml