CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    account_id VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS stations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    CONSTRAINT unique_lat_lon UNIQUE (latitude, longitude)
);

CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50) NOT NULL CHECK (type IN ('CAR', 'SCOOTER', 'KICK_SCOOTER')),
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE', 'RESERVED', 'RENTED', 'MAINTENANCE', 'CHARGING')),
    battery_level INT CHECK (battery_level >= 0 AND battery_level <= 100),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    station_id BIGINT,
    
    CONSTRAINT fk_vehicle_station 
        FOREIGN KEY (station_id) 
        REFERENCES stations(id)
        ON DELETE SET NULL
);


INSERT INTO stations (name, latitude, longitude) VALUES 
    ('Stazione Centrale', 44.5058, 11.3432),
    ('Piazza Maggiore', 44.4939, 11.3428),
    ('Via Irnerio', 44.4998, 11.3499),
    ('Porta San Felice', 44.4981, 11.3283),
    ('Via delle Lame', 44.5015, 11.3361)
ON CONFLICT DO NOTHING;


INSERT INTO vehicles (type, status, battery_level, latitude, longitude, station_id) VALUES 
    ('SCOOTER', 'AVAILABLE', 92, 44.4949, 11.3426, 1),
    ('KICK_SCOOTER', 'AVAILABLE', 78, 44.4968, 11.3396, 2),
    ('CAR', 'AVAILABLE', 55, 44.5008, 11.3512, 3),
    ('SCOOTER', 'AVAILABLE', 88, 44.4901, 11.3303, 4),
    ('KICK_SCOOTER', 'AVAILABLE', 41, 44.5045, 11.3489, 5)
ON CONFLICT DO NOTHING;


INSERT INTO users (name, email, password, account_id) VALUES 
    ('Test User', 'user@acme.com', 'password123', 'account-67890'),
    ('Admin', 'a@a.a', 'aaaaaaaa', 'account-12345')
ON CONFLICT DO NOTHING;